<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <RootNamespace>Ngr.Launcher.App</RootNamespace>
    <AssemblyName>Ngr.Launcher</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ngr.Launcher.Core\Ngr.Launcher.Core.csproj" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="WPF-UI.Tray" Version="4.3.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>
</Project>
